### ISSUE TITLE
StringTable: iterator invalidation is impossible

### ISSUE THREAD

**Issue by steveklabnik** [Robbepop/cionc#7] opened 2016-02-26 21:55 UTC
> ```
> /* I use Box<String> because of possible iterator invalidation
>   in case the Vec is growing in size and reallocating memory. */
> ```

Rust prevents iterator invalidation at compile-time, so this should never happen. Also, I'm not sure how a Box would solve it.

This indirection shouldn't be needed at all. I could send a patch, but was curious to hear more about why you wrote this comment :smile:

**Comment by Robbepop** [comment] 2016-02-26 23:52
"Rust prevents iterator invalidation at compile-time" - okay, big time! :O 
I can't imagine how this is possible, maybe I am missing something but it sounds awesome!
In my understanding Rust uses value-types to store thing in collections like Vec like in C++ so the elements are stored memory-aligned and densely in the memory.
If you don't work with indirections in C++ all references (iterators) pointing to the memory are invalidated once the memory gets reallocated due to a growth of the Vec.
So pointers to the old elements are invalid since those are now out of scope.
As far as I can imagine Rust prevents this with the borrow-checker which is not allowing & and &mut at the same time to the same object.
However, there can be many & to the same object in a Vec (especially in my case with a StringTable which owns all the Strings and has many & borrows to the outside world.) So this means that it either can not reallocate its buffer, all iterators (references) are invalidated, or that this datastructure works completely different than my current understanding.
With an additional indirection of a Box<String> one could just invalidate pointers to the Boxes instead of the pointers to what the Box stores at the heap, so that's how you normally fix iterator invalidation in C++ - besides not having iterators to the outside at all. :D

**Comment by steveklabnik** [comment] 2016-02-26 23:56
If you have one or many `&` borrows out on something, then you cannot have mutable access, so you can't reallocate the buffer, so that can't happen, basically. :)

Here's an example: http://is.gd/JlFyvf

The key insight is this:

> there can be many & to the same object in a Vec

This causes the Vec to be borrowed as well.

**Comment by Robbepop** [comment] 2016-02-27 00:26
That's turning into a problem for me as far as I can imagine.
At least it makes it hard to insert new entries to my StringCache once the first String is inserted into it and stored as a reference.
The problem is that the Lexer outputs Tokens that can themselves store a &str which is just a reference to a String stored in the StringCache that owns those Strings.
I planned that it is possible to add new Strings to the StringCache with the `get_or_insert(s: String) -> &str` method, however, once the Tokens store the returned reference the StringCache couldn't add any new Strings to it which is bad ... :/

**Comment by steveklabnik** [comment] 2016-02-27 01:02
This also might be a good topic for users, actually?

**Comment by Robbepop** [comment] 2016-02-27 12:28
yep: http://users.rust-lang.org/t/how-to-structure-this-program-for-my-use-cases/4780

**Closed as completed** 2016-02-27 12:39 UTC
